### ISSUE TITLE
Include banner/text about reports/download feature coming soon

### ISSUE THREAD

**Issue by achlong** [Hyperobjekt/el-map#17]
Since we're not including the reports feature in the first release, we want to add a note somewhere indicating that it will soon be accessible. Probably makes most sense to add in this "get the data" section:
![Screen Shot 2022-05-17 at 1 35 44 PM](https://user-images.githubusercontent.com/90058829/168905347-63552f84-7382-4386-bd0e-f02edde532c8.png)

**Comment by hoshmn** [comment]
Not sure I understand, I think the Get the data feature will be functional?

<img width="1074" alt="Screen Shot 2022-05-19 at 7 35 52 PM" src="https://user-images.githubusercontent.com/18331999/169437430-fcd2c974-d7dd-4384-8697-b2db4985841a.png">
Get the Data is a separate feature from Reports. On the live site, clicking Get the Data takes you to https://evictionlab.org/get-the-data/ and if you click Get Data there it takes you to https://data-downloads.evictionlab.org/

As for letting users know the Reports feature is coming soon, should we just disable the SELECT REPORT(S) button (shown above) and have it say "Coming soon!" or something in the copy above it?

**Comment by hoshmn** [comment]
@james-minton I think Hannah said you'd be doing this, is that right? I can do it if not, but will need to better understand what's wanted (seems like maybe this is for the container site, whereas I was interpreting it as for the map app)

**Comment by james-minton** [comment]
Thanks @hoshmn , I would just change the button to read "coming soon."
<img width="350" alt="Screen Shot 2022-05-31 at 2 25 53 PM" src="https://user-images.githubusercontent.com/33635008/171258561-e0308e0c-a185-4110-93a0-556fee247753.png">
