### ISSUE TITLE
FAQ copy updates

### ISSUE THREAD

**Issue by achlong** [Hyperobjekt/el-map#19]
client finalizing copy edits by May 20

**Comment by achlong** [comment]
Spanish: https://docs.google.com/document/d/17zt6KQG29m9bVrtBG-hSrqme2kMyfN2g-ylki2zi2Io/edit

**Comment by hoshmn** [comment]
@james-minton just to be sure, this is on the main site and you're getting this done?

**Comment by james-minton** [comment]
@hoshmn correct!
