### ISSUE TITLE
Alpha change requests

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/el-map#24]
Rounding up action items from alpha feedback:

- [x] Add option to not select a Census variable
- [x] Filing Rate tooltip: “98% evictions were filed for every 100 renter households” **shouldn’t have %**
- [x] Cards/data tables text: use only 1 decimal place for all rates. Currently values <1 can have 2 decimal places -- use rounding where necessary to get to 1 decimal place
- [x] Maryland flag needs application to “modeled data” also. (I think Maryland is the sole instance where a flag is used in modeled data?)
- [x] Fix "Data quality is indicated by X flags"
- [x] Animate first card that appears when selecting a location
- [x] Add downward carrot or some other indication that “MODELED DATA” is a toggle -- Sasha to advise
- [x] NEW: Make initial popup "first load only" with cookie or other approach. Or better: check box for "Don't show again"
- [x] Users are noticing that the address search seems to be more restrictive/less responsive than in earlier map. Please try typing "222 w 135" in the new map vs t[he old map](https://evictionlab.org/map/#/2016?geography=states&type=er) for an example.
- [x] Fix all broken links in popup/elsewhere (reference client channel/doc for missing links)
- [x] Change popup text to "Toggle the Map from “Modeled” to “Original” to view our original map. This map displays eviction filings, households threatened with eviction, and eviction judgments from proprietary data at every level of geography from states to block groups. Because we know that these data are incomplete for certain areas, we include data-quality flags to aid in interpretation. Read how these data were incorporated into our estimates here."
- [x] Also change popup text to "“What’s different about using estimates?” When you use our data, be sure to do so correctly. With some of our data, you can run a wide range of analyses. But when the data are based on estimates, you need to be careful. For more information, [see our FAQ](https://evictionlab.org/help-faq).

**Comment by hoshmn** [comment]
@james-minton thanks for consolidating 🙏 

Regarding the last 3 (links + popup copy): 
I don't see where the urls are supplied. For the copy changes, I don't know where exactly the links should be "interpolated" (which words should be made into links). I also assume there should be corresponding changes to the Spanish copy. Could you make the changes directly to the [copy doc](https://docs.google.com/document/d/1TQeXLcdNr7PZ9mxp1hZXPp9JyGGA-VTtzPJH5FWgW8o/edit) or have the client do so?
